# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dbfe68f3ac6c5fee25442bf4ca5a49d85d31de14cc425d5c3a781927acfae56c7cd9019b5d192ea5b817e23ec2a0e9c85699b77c924f8999e9172ce7a871afb

test:
  secret_key_base: ace50e7ce7e2b16fc5c4e8b746d132b8b55b6b1e17b406f3406a8f02ed412a08130b62e9e45308570f3751e32e2ac71c6397ff7c16b7742dcaa3115aca096646

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
